server:
  error:
    whitelabel:
      enabled: true
  port: 8080

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/auth/
  kafka:
    bootstrap-servers: #host:port
    consumer:
      group-id: "myGroup"

app:
  security:
    jwt:
      keystore-location: keys/cnat-jwt-signing.jks
      password: #password
      key-alias: jwtsigning
      passphrase: #passphrase
  kafka:
    topics:
      tracker-data-register: tracker-data-register
