server:
  error:
    whitelabel:
      enabled: true
  port: 8080

spring:
  kafka:
    bootstrap-servers: #host:9092
    consumer:
      group-id: "myGroup"

app:
  security:
    jwt:
      keystore-location: keys/cnat-jwt-signing.jks
      password: #password
      key-alias: jwtsigning
      passphrase: #passphrase
  kafka:
    topics:
      tracker-data-register: tracker-data-register
  cnat:
    user-service: http://localhost:8082
