server:
  port: 80
  error:
    include-message: always

#logging:
#  level:
#    org.springframework.security.web: DEBUG

spring:
  kafka:
    bootstrap-servers: ${CNAT_KAFKA_URI}
    consumer:
      group-id: "myGroup"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  security:
    jwt:
      keystore-location: keys/keystore.jks
      password: ${CNAT_API_GATEWAY_KEYSTORE_PASSWORD}
      key-alias: ${CNAT_API_GATEWAY_JWT_KEY_ALIAS}
      passphrase: ${CNAT_API_GATEWAY_JWT_KEY_PASSWORD}
  kafka:
    topics:
      tracker-data-register: tracker-data-register
  cnat:
    tracker-service: ${CNAT_TRACKER_SERVICE_URI}
    user-service: ${CNAT_USER_SERVICE_URI}
    web-app: http://localhost:30080

springdoc:
  api-docs:
    path: /api-docs
