server:
  error:
    whitelabel:
      enabled: true
  port: 8080

spring:
  kafka:
    bootstrap-servers: #host:9092
    consumer:
      group-id: "myGroup"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  security:
    jwt:
      keystore-location: keys/cnat-jwt-signing.jks
      password: #password
      key-alias: jwtsigning
      passphrase: #passphrase
  kafka:
    topics:
      tracker-data-register: tracker-data-register
  cnat:
    user-service: http://localhost:8082
    tracker-service: http://localhost:8081

springdoc:
  api-docs:
    path: /api-docs
